[workspace]
resolver = "2"
members = [
    "generated/pricing-programs/*",
    "generated/s_controller_interface",
    "generated/sol-value-calculator-programs/*",
    "keys/*",
    "libs/pricing-programs/*",
    "libs/s-controller-lib",
    "libs/sanctum-utils",
    "libs/sanctum-onchain-utils",
    "libs/sol-value-calculator-programs/*",
    "libs/s-controller-lib",
    "programs/pricing-programs/*",
    "programs/s-controller",
    "programs/sol-value-calculator-programs/*",
    "test-utils"
]

[workspace.dependencies]
bincode = "^1"
borsh = ">=0.9" # TODO: there are probably gonna be issues from having both 0.9 and 0.10 in the workspace but idk how to fix this bec solana-program depends on both
bytemuck = "^1"
num-derive = ">=0.3"
num-traits = ">=0.2"
proptest = "^1"
sanctum-macros = { git = "https://github.com/igneous-labs/sanctum-macros", branch = "master" }
serde = "^1"
serde_json = "^1"
spl-token = "*"
spl-associated-token-account = "*"
static_assertions = "^1"
thiserror = "^1"
tokio = "^1"

# DO NOT ENABLE `features = ["solana-sdk"]` HERE OR ELSE IT'LL MAKE ALL ONCHAIN PROGRAMS UNCOMPILABLE
# CLIENT CRATES SHOULD ENABLE IT SEPARATELY
solana-readonly-account = { git = "https://github.com/igneous-labs/solana-readonly-account", branch = "master" }

# solana libraries (not pure rust)
# Use * for flexibility for library users, but lock to 1.16 for development
solana-account-decoder = "*"
solana-program = "*"
solana-program-test = "*"
solana-sdk = "*"
