[package]
name = "marinade-calculator"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
borsh = { workspace = true }
generic_pool_calculator_interface = { workspace = true }
generic-pool-calculator-lib = { workspace = true }
generic-pool-calculator-onchain = { workspace = true }
marinade_calculator_interface = { workspace = true }
marinade-calculator-lib = { workspace = true }
sanctum-onchain-utils = { workspace = true }
sol-value-calculator-onchain = { workspace = true }
solana-program = { workspace = true }

[dev-dependencies]
generic-pool-calculator-test-utils = { workspace = true }
sanctum-solana-test-utils = { workspace = true }
sanctum-token-ratio = { workspace = true }
solana-program-test = { workspace = true }
solana-readonly-account = { workspace = true, features = ["solana-sdk"]}
solana-sdk = { workspace = true }
test-utils = { workspace = true }
tokio = { workspace = true }
