[package]
name = "lido-calculator"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
borsh = { workspace = true }
generic_pool_calculator_interface = { path = "../../../generated/sol-value-calculator-programs/generic_pool_calculator_interface" }
generic-pool-calculator-lib = { path = "../../../libs/sol-value-calculator-programs/generic-pool-calculator-lib" }
generic-pool-calculator-onchain = { path = "../../../libs/sol-value-calculator-programs/generic-pool-calculator-onchain" }
lido_calculator_interface = { path = "../../../generated/sol-value-calculator-programs/lido_calculator_interface" }
lido-calculator-lib = { path = "../../../libs/sol-value-calculator-programs/lido-calculator-lib" }
sanctum-onchain-utils = { path = "../../../libs/sanctum-onchain-utils" }
sol-value-calculator-onchain = { path = "../../../libs/sol-value-calculator-programs/sol-value-calculator-onchain" }
solana-program = { workspace = true }

[dev-dependencies]
generic-pool-calculator-test-utils = { path = "../../../libs/sol-value-calculator-programs/generic-pool-calculator-test-utils" }
solana-program-test = { workspace = true }
solana-readonly-account = { workspace = true, features = ["solana-sdk"]}
solana-sdk = { workspace = true }
test-utils = { path = "../../../test-utils" }
tokio = { workspace = true }
