[package]
name = "wsol-calculator"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []
testing = [] # not used, added so that we can run cargo-test-sbf at workspace root to test all programs

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sanctum-misc-utils = { workspace = true }
sol-value-calculator-onchain = { workspace = true }
solana-program = { workspace = true }
wsol-calculator-lib = { workspace = true }
wsol_calculator_interface = { workspace = true }