[package]
name = "wsol-calculator"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sanctum-onchain-utils = { path = "../../../libs/sanctum-onchain-utils" }
sol-value-calculator-onchain = { path = "../../../libs/sol-value-calculator-programs/sol-value-calculator-onchain" }
solana-program = { workspace = true }
wsol-calculator-lib = { path = "../../../libs/sol-value-calculator-programs/wsol-calculator-lib" }
wsol_calculator_interface = { path = "../../../generated/sol-value-calculator-programs/wsol_calculator_interface" }