[package]
name = "s-controller"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
borsh = { workspace = true }
s_controller_interface = { path = "../../generated/s_controller_interface" }
s-controller-lib = { path = "../../libs/s-controller-lib" }
sanctum-utils = { path = "../../libs/sanctum-utils" }
sanctum-onchain-utils = { path = "../../libs/sanctum-onchain-utils" }
sol_value_calculator_interface = { path = "../../generated/sol-value-calculator-programs/sol_value_calculator_interface" }
solana-program = { workspace = true }