[package]
name = "s-controller"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
s_controller_interface = { path = "../../generated/s_controller_interface" }
s-controller-lib = { path = "../../libs/s-controller-lib" }
solana-program = { workspace = true }